// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.layout.display-list.retain", true);
user_pref("app.normandy.startupRolloutPrefs.security.tls.version.fallback-limit", 4);
user_pref("app.normandy.user_id", "598b42cc-4c93-4c77-a9ce-d01bf7d91e8d");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1601580613);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1601580733);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1601581093);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1601581333);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1601581213);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1601580973);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1601580853);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1533321325);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c1124b4a-4be0-4624-b803-ece42598b800}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1533265200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.finished", true);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1599764910);
user_pref("browser.onboarding.notification.prompt-count", 4);
user_pref("browser.onboarding.notification.tour-ids-queue", "");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.state", "watermark");
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1601582430430");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1601584212430");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1601580600457");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1601584200457");
user_pref("browser.search.countryCode", "BR");
user_pref("browser.search.region", "BR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180704192850");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1601580587");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20180704192850");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1533321333261");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Tue, 22 Sep 2020 11:07:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1601580614);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180704192850");
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"f88af390-ee75-4903-84f0-b7af9b74791d\",\"screenshots@mozilla.org\":\"021cd7db-544e-4971-b394-77e2dcea796c\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1601581419);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1601580617);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180704192850");
user_pref("media.gmp-manager.lastCheck", 1601580675);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1601581419);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "5af683ec-69c4-4c9d-862c-1bd283d77952");
user_pref("services.blocklist.addons.checked", 1601579745);
user_pref("services.blocklist.gfx.checked", 1601579745);
user_pref("services.blocklist.onecrl.checked", 1601579745);
user_pref("services.blocklist.pinning.checked", 1601579745);
user_pref("services.blocklist.plugins.checked", 1601579745);
user_pref("services.settings.clock_skew_seconds", 988);
user_pref("services.settings.last_etag", "\"1601577430990\"");
user_pref("services.settings.last_update_seconds", 1601579745);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1601581419);
user_pref("toolkit.startup.last_success", 1601580582);
user_pref("toolkit.telemetry.cachedClientID", "4ac0260c-b480-453b-9f91-4c9470639442");
user_pref("toolkit.telemetry.previousBuildID", "20180704192850");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
